# Generated by Django 4.1.5 on 2023-02-10 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_cart_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='item',
            new_name='items',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
